ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,151 +1,114 @@
-name: Run all tests
+name: Moodle Plugin CI
 
-# Run this workflow every time a new commit pushed to your repository
 on: [push, pull_request]
 
 jobs:
-  setup:
-    runs-on: ubuntu-latest
+  test:
+    runs-on: ubuntu-22.04
+
     services:
       postgres:
-        image: postgres:10
+        image: postgres:13
         env:
           POSTGRES_USER: 'postgres'
           POSTGRES_HOST_AUTH_METHOD: 'trust'
-        # Health check to wait for postgres to start.
         ports:
-          - 5432:5432
+        - 5432:5432
         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
+
       mariadb:
-        image: mariadb:10.5
+        image: mariadb:10
         env:
           MYSQL_USER: 'root'
           MYSQL_ALLOW_EMPTY_PASSWORD: "true"
+          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
+          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
         ports:
-          - 3306:3306
+        - 3306:3306
         options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
+
     strategy:
       fail-fast: false
       matrix:
-        include:
-#          - moodle-branch: 'MOODLE_400_STABLE'
-#            php: '7.4'
-#            database: 'mariadb'
-#          - moodle-branch: 'MOODLE_400_STABLE'
-#            php: '7.4'
-#            database: 'pgsql'
-#          - moodle-branch: 'MOODLE_401_STABLE'
-#            php: '8.0'
-#            database: 'mariadb'
-#          - moodle-branch: 'MOODLE_401_STABLE'
-#            php: '8.0'
-#            database: 'pgsql'
-#          - moodle-branch: 'MOODLE_402_STABLE'
-#            php: '8.1'
-#            database: 'mariadb'
-#          - moodle-branch: 'MOODLE_402_STABLE'
-#            php: '8.1'
-#            database: 'pgsql'
-          - moodle-branch: 'MOODLE_403_STABLE'
-            php: '8.2'
-            database: 'mariadb'
-          - moodle-branch: 'MOODLE_403_STABLE'
-            php: '8.2'
-            database: 'pgsql'
-          - moodle-branch: 'MOODLE_404_STABLE'
-            php: '8.3'
-            database: 'mariadb'
-          - moodle-branch: 'MOODLE_404_STABLE'
-            php: '8.3'
-            database: 'pgsql'
-          - moodle-branch: 'MOODLE_405_STABLE'
-            php: '8.3'
-            database: 'mariadb'
-          - moodle-branch: 'MOODLE_405_STABLE'
-            php: '8.3'
-            database: 'pgsql'
+        php: ['8.1', '8.2', '8.3', '8.4']
+        moodle-branch: ['MOODLE_405_STABLE', 'MOODLE_404_STABLE']
+        database: [pgsql, mariadb]
+
     steps:
-      - name: Check out repository code
-        uses: actions/checkout@v2
-        with:
-          # Clone in plugin subdir, so we can setup CI in default directory.
-          path: plugin
+    - name: Check out repository code
+      uses: actions/checkout@v4
+      with:
+        path: plugin
 
-      - name: Install node
-        uses: actions/setup-node@v1
-        with:
-          # TODO: Check if we can support .nvmrc
-          node-version: '14.15.0'
+    - name: Setup PHP ${{ matrix.php }}
+      uses: shivammathur/setup-php@v2
+      with:
+        php-version: ${{ matrix.php }}
+        extensions: ${{ matrix.extensions }}
+        ini-values: max_input_vars=5000
+        # If you are not using code coverage, keep "none". Otherwise, use "pcov" (Moodle 3.10 and up) or "xdebug".
+        # If you try to use code coverage with "none", it will fallback to phpdbg (which has known problems).
+        coverage: none
 
-      - name: Setup PHP environment
-        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
-        with:
-          php-version: ${{ matrix.php }}
-          extensions: mbstring, pgsql, mysqli
-          tools: phpunit
+    - name: Initialise moodle-plugin-ci
+      run: |
+        composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
+        echo $(cd ci/bin; pwd) >> $GITHUB_PATH
+        echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
+        sudo locale-gen en_AU.UTF-8
+        echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV
 
-      - name: Deploy moodle-plugin-ci
-        run: |
-          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
-          # Add dirs to $PATH
-          echo $(cd ci/bin; pwd) >> $GITHUB_PATH
-          echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
-          # PHPUnit depends on en_AU.UTF-8 locale
-          sudo locale-gen en_AU.UTF-8
-      - name: Install moodle-plugin-ci
-        # Need explicit IP to stop mysql client fail on attempt to use unix socket.
-        run: moodle-plugin-ci install -vvv --plugin ./plugin --db-host=127.0.0.1
-        env:
-          DB: ${{ matrix.database }}
-          # TODO: Omitted MOODLE_BRANCH results in regex failure, investigate.
-          MOODLE_BRANCH: ${{ matrix.moodle-branch }}
+    - name: Install moodle-plugin-ci
+      run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
+      env:
+        DB: ${{ matrix.database }}
+        MOODLE_BRANCH: ${{ matrix.moodle-branch }}
+        # Uncomment this to run Behat tests using the Moodle App.
+        # MOODLE_APP: 'true'
 
-      - name: Run phplint
-        if: ${{ always() }}
-        run: moodle-plugin-ci phplint
+    - name: PHP Lint
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci phplint
 
-      - name: Run phpcpd
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpcpd || true
+    - name: PHP Mess Detector
+      continue-on-error: true # This step will show errors but will not fail
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci phpmd
 
-      - name: Run phpmd
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpmd
+    - name: Moodle Code Checker
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci phpcs --max-warnings 0
 
-      - name: Run codechecker
-        if: ${{ always() }}
-        run: moodle-plugin-ci codechecker
+    - name: Validating
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci validate
 
-      - name: Run validate
-        if: ${{ always() }}
-        run: moodle-plugin-ci validate
+    - name: Check upgrade savepoints
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci savepoints
 
-      - name: Run savepoints
-        if: ${{ always() }}
-        run: moodle-plugin-ci savepoints
+    - name: Mustache Lint
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci mustache
 
-      - name: Run mustache
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpcpd || true
-        env:
-          MUSTACHE_IGNORE_NAMES: mobile_teacher_form.mustache
+    - name: PHPUnit tests
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci phpunit --fail-on-warning
 
-      - name: Run grunt
-        if: ${{ always() }}
-        run: moodle-plugin-ci grunt
+    - name: Behat features
+      id: behat
+      if: ${{ !cancelled() }}
+      run: moodle-plugin-ci behat --profile chrome
 
-      - name: Run phpdoc
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpdoc
+    - name: Upload Behat Faildump
+      if: ${{ failure() && steps.behat.outcome == 'failure' }}
+      uses: actions/upload-artifact@v4
+      with:
+        name: Behat Faildump (${{ join(matrix.*, ', ') }})
+        path: ${{ github.workspace }}/moodledata/behat_dump
+        retention-days: 7
+        if-no-files-found: ignore
 
-#      - name: Run phpunit
-#        if: ${{ always() }}
-#        run: |
-#             moodle-plugin-ci phpunit
-#             cd moodle
-#             vendor/bin/phpunit --fail-on-risky --disallow-test-output --filter tool_dataprivacy_metadata_registry_testcase
-#             vendor/bin/phpunit --fail-on-risky --disallow-test-output --testsuite core_privacy_testsuite --filter provider_testcase
-
-#      - name: Run behat
-#        if: ${{ always() }}
-#        run: moodle-plugin-ci behat --profile chrome
+    - name: Mark cancelled jobs as failed.
+      if: ${{ cancelled() }}
+      run: exit 1
